common: &common
  facebook:
    api_key: "468833256565511"
    api_secret: "0ecf34e9e62026f3a797731e264e664a"
  url: "http://localhost:3000"

development:
  <<: *common

test:
  <<: *common

production:
  facebook:
    api_key: ""
    api_secret: ""
  url: "http://"

staging:
  facebook:
    api_key: ""
    api_secret: ""
  url: "http://"
